server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          search-paths: spring-cloud-config/config-repo
          uri: https://github.com/JoyHwong/blog-demo-source.git

